### ISSUE TITLE
[RFC] Bonus Items-of-the-Month

### ISSUE THREAD

**Issue by bearsdotzone** [loathers/greenbox#100]
October 2024 has a bonus item of the month in the photo booth sized crate. Greenbox doesn't have a solution for displaying two items of the month. The wiki and av-snapshot both solve this issue by jamming the items into the same box. I mocked that up for greenbox and it looks _okay_. On the other hand, a redesign of the IotMs section could address this issue and #43.

![image](https://github.com/user-attachments/assets/0b7f1b01-83a9-4b22-a3aa-4d45da910657)
![image](https://github.com/user-attachments/assets/ec6df596-81f6-44bc-a49b-455cbc9ece6b)

**Comment by gausie** [comment]
Why would we redesign the iotms section to include an extra Clan VIP key?

**Comment by bearsdotzone** [comment]
Most of the bonus iotms aren't VIP keys, the issue is just pertinent because of this month's VIP key.

**Comment by gausie** [comment]
what are the other bonus iotms?

**Comment by gausie** [comment]
Oh you mean the emo roe. I don't want to have a greenbox for that

**Comment by gausie** [comment]
And tcw is available every year
