### ISSUE TITLE
More granular categorization of skills

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/greenbox#26]
gnome skills, clan dungeon skills (sorted by clan dungeon?), path perms, pvp skills, etc

**Comment by docrostov** [comment]
i support this but i think this should probably come with a broader discussion about filtering and categorization. one of the points of greenbox was that once we get all this data staged, it should be easier to allow end users to apply filters to their greenbox; things like "only look at items in standard", "only look at avatar paths", etc. my big question here is that outside of just skills, what are other generalized categories we want to implement, and what is the best way to store and document this information without building a big system of manual filters that we someday have to untangle to add better user-driven filtering.
