### ISSUE TITLE
List maximum possible level for skills with levels

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/greenbox#30]
Instead of saying I have 10 slimy synapses, say 10/10; instead of saying I have 3 numberology, say I have 3/x (I don't know offhand what x is)

**Comment by gausie** [comment]
If someone collects these data for me I will do this very quickly

**Comment by Tokoeka** [comment]
Slimy Sinews (0046): 10
Slimy Synapes (0047): 10
Slimy Shoulders (0048): 10
Summon Annoyance (107): 9
Belch The Rainbow (117): 11
Summon Holiday Fun (121): currently 6
Bear Essence (134): Currently 6
Calculate The universe (144): currently 4
Experience Safari (180): currently 4
Toggle Optimality (7254): currently 3

These are the only skills i am aware of with levels

**Comment by gausie** [comment]
Pirate Bellow: 6, Summon Carrot: 5, Implode Universe: 13

**Comment by gausie** [comment]
Done
