### ISSUE TITLE
Show number of golds, silvers, bronzes

### ISSUE THREAD

**Issue by pstalcup** [loathers/greenbox#33]
Optionally tie them to the path they came from - I am not sure that this is currently possible without reading every single DC?

**Comment by gausie** [comment]
I think this is infeasible. I think we'd probably check your charsheet for how many badges you have and then traverse path leaderboards until they're all accounted for. Seems not worth it

**Comment by docrostov** [comment]
i agree. i would absolutely love this, as someone with golds/silvers, but until this information is derivable on your character sheet i think the best we could do is parse koldb with date limitations, which sounds absolutely fucking terrible.

**Comment by gausie** [comment]
Going to close until someone can come up with a smarter way of doing this
