### ISSUE TITLE
Missed ItoMs in my case.

### ISSUE THREAD

**Issue by djve60** [loathers/greenbox#36]
Just run greenbox and I'm in aftercore and the code missed 4 items that I see:

[1. LT&T telegraph office deed should go green when you don't have the deed but do have LT&T Office on the right side of the tracks.
2. Detective School application should go green when you don't have the form but do have 11th Precinct Headquarters on the wrong side of the tracks.
3. Heart-shaped crated should go green when you don't have the item but do have a Tunnel of  L.O.V.E. on the wrong side of the tracks.
These 3 were also an issue with the old cc_snapshot but I'm reporting it here.
4. antique nutcracker figurine that becomes the antique nutcracker was not detected in Hagnk's when other proto-familiars were.
This did work in the old tool.] - **Addressed below.**

If these issues are not to be fixed is there way to manually trigger recognition?

I will say the code runs very, very fast.

UI issues:
I miss the smaller output and layout from the old, abandoned snapshot. Things like the skill table showing pre and post class revamp and the level was handy. Also the different sizes of images in each section seems a little strange. 

Maybe to make the output more concise would a text only version work?

Finally the old snapshot tool did have <URL>/<player name> output. This made it easy to share your status. If it's not planned I would like to see, at some point, the same ability. This would mean the data would need to be saved on the server, obviously, rather than the current dynamic URL shown in Mafia.

These are all quite minor issues and congratulations on getting a replacement going.

**Comment by Rinn** [comment]
1. `set telegraphOfficeAvailable=true`
2. `set hasDetectiveSchool=true`
3. `set loveTunnelAvailable=true`
4. There isn't special listing for any of the familiars, it just checks of you have the $familiar.hatchling in your inventory or storage, I don't see anything amiss with the greenbox code

**Comment by djve60** [comment]
Ah... the "set <var>=true" works like a charm. Is it worth starting FAQ doc for trivial issues like this?

 I was expecting more than just looking at the mafia settings file. such as doing calls to KoL. I see now I was overly ambitious in what was possible.

**Comment by Rinn** [comment]
The intention is to use what mafia is already tracking, rather than doing page hits to gather the data.

**Comment by djve60** [comment]
Ah. Then that makes sense. Just the UI issues, which may be the team doesn't care about, and it's not critical. 
I think you can close this ticket. 

Thanks for letting me know.

**Comment by gausie** [comment]
> I think you can close this ticket.

Oh well since you think so I'll get right to it 😉
