### ISSUE TITLE
Wrong Tattoo

### ISSUE THREAD

**Issue by jaadams5** [loathers/greenbox#80]
Greenbox reports that a never-ascended character has "G-Lover Gattoo" as a tattoo.  The character doesn't have it.  Greenbox fails to show the Guzzlr tattoo which the character does have,

Perhaps of interest, av-snapshot does not show a G-Lover tattoo and has something it calls "Guzzlr Tattoo 2" which it thinks the character does not have.

https://greenbox.loathers.net/?u=215957

https://api.aventuristo.net/av-snapshot?u=fronobulax#a1b

Thank you.

**Comment by gausie** [comment]
Could you send me the contents of your account_tattoos.php?

**Comment by jaadams5** [comment]
[account_tattoos.php.html.txt](https://github.com/loathers/greenbox/files/15391948/account_tattoos.php.html.txt)

OK?

**Comment by gausie** [comment]
> [account_tattoos.php.html.txt](https://github.com/loathers/greenbox/files/15391948/account_tattoos.php.html.txt)
> 
> OK?

No, you've hit save on the KoLmafia relay browser here which is doubly wrong. Please either get it from KoLmafia debug log, or directly from the KoL website and just View Source, copy and paste.

**Comment by jaadams5** [comment]
<body> extracted.

The debug log had more info than I expect you needed.   If this is still not what you want I'll try again tomorrow.

**Comment by gausie** [comment]
Actually no, replicating your exact situation isn't trivial, it would be great for you to provide the actual HTML.

Just for an update, writing a test suite for Greenbox necessitated an update to libram, which wasn't merged until now. I believe I've now fixed at least half of your issue. Please get me the HTML and I'll make sure everything is right.

**Comment by jaadams5** [comment]
Thank you.  It was frustrating to not understand and follow directions.

The previous file was created by viewing the profile in the relay browser, turning on mafia debug, selecting the view your tattoos link and then turning off debug.  I then used an editor to isolate what was between body tags.

I logged into plain vanilla KOL, navigated to the page, displayed the tattoos and then did a Save from the tattoo frame.  That produced a single HTML file and a subdirectory containing a number of files, many of which were images, but not all.  If we have to do this again what would you like?  In the absence of any guidance I will create a clean subdirectory, save to there and then zip up the formerly clean subdirectory.

I'm using Brave on Windows 10 Home.  I could easily try the same thing in Microsoft Edge if that is needed.

Please advise if "Please get me the HTML and I'll make sure everything is right." still applies and I will try and get what you need.

Thank you.

**Comment by gausie** [comment]
@jaadams5 as I said in my first request

> Please either get it from KoLmafia debug log, or directly from the KoL website and just View Source, copy and paste.

Both files that you sent were generated using the browser's save feature. It's very clear that none of it comes from the KoLmafia debug log, nor from viewing source on vanilla KoL.

Getting the HTML from either of those sources would still be appreciated.

**Comment by gausie** [comment]
That simply cannot be the case. Every file posted to this issue before now was sourced from "Save As". I suspect you uploaded the wrong file by mistake.

The most recent upload is correct though, thank you.

**Comment by jaadams5** [comment]
OK.  I'll chalk up another one to faulty memory.   Glad this works, which is really all that matters.  Thanks.
