### ISSUE TITLE
No greenbox data found

### ISSUE THREAD

**Issue by pjdo** [loathers/greenbox#89]
I am calling the script, and mafia says everything goes fine:

```
> greenbox

Deciding your fate...
All done! To see your greenboxes, visit: https://greenbox.loathers.net/?u=2455701
```

Then I go to the page, and after some loading time I see the error `No greenbox data found`.

This may or may not be related to another issue. A few days ago I wanted to do a fresh start and called `greenbox --wipe`. After that I started getting infinite KMail from **Jalen Arbuckle** confirming successful data wipe, I had to add him to ignore list. I wonder if that request started an infinite loop that is still running, constantly deleting my data, and this is why new requests show an empty page?

**Comment by gausie** [comment]
The request won't still be running but ignoring Jalen Arbuckle will break
greenbox I think. I need to sort the wipe issue!

**Comment by pjdo** [comment]
I removed Jalen Arbuckle from the ignore list, ran `greenbox` command again and I can now see my stats. It works!

**Comment by gausie** [comment]
Great. It'll now only send one message, and I have some error reporting in place to see what is going on.
