### ISSUE TITLE
Receiving KMails: There was an error processing your greenbox submission.

### ISSUE THREAD

**Issue by SaneBread** [loathers/greenbox#91]
I have greenbox as part of my post-prism script. For the last 2 weeks or so, I've been getting messages from Jalen Arbuckle telling me There was an error processing your greenbox submission. Sometimes more than one, and they only come in hours after I actually ran the greenbox update. The update itself seems to work fine though.

<img width="526" alt="Screenshot 2024-07-24 at 09 38 22" src="https://github.com/user-attachments/assets/e24b30f5-b811-4e9e-a804-035dd078b79f">

**Comment by gausie** [comment]
It'll now only send one message, and I have some error reporting in place to see what is going on.

**Comment by SaneBread** [comment]
@gausie just now I received 2 messages again from JA

![Screenshot 2024-07-26 at 19 25 03](https://github.com/user-attachments/assets/4326abe9-0e1c-44d8-85cf-2d24185ef990)

(times are in CEST)

**Comment by gausie** [comment]
Now definitively fixed, sorry
