### ISSUE TITLE
Mark of the Vampire and Mark of the Ghost tattoo names are swapped.

### ISSUE THREAD

**Issue by poshpotato** [loathers/greenbox#94]
![image](https://github.com/user-attachments/assets/e669c9e8-9ce4-4a38-8717-032338d8a497)
Screenshot taken with mark of the vampire and without mark of the ghost.

**Comment by bustarhymes69** [comment]
Have a PR to fix all mislabeled tattoos

**Comment by gausie** [comment]
Thanks busto
